#!/usr/bin/env python3
"""Generate docs/stage1/WIRING.md (BOM + point-to-point tables) from design.py."""
import os
import design as D

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
L = []
w = L.append
w("# Stage 1 wiring: Arduino Nano (328P) + 2 × MCP23S17\n")
w("Generated by `tools/wiring.py` from `tools/design.py`, the same data the schematic sheets use. Do not edit by hand.\n")
w("Sheets: `sch-0-blocks` (index) · `sch-1-power` · `sch-2-mcu` · `sch-3-pin-drivers` · `sch-4-chip-power` · `sch-5-zif`.\n")

w("## ZIF contacts\n")
w("| ZIF | Driven from (through its own 220 Ω) | Also switched to |")
w("|---|---|---|")
hs = {z: (q, n) for q, z, n, _ in D.HIGH_SIDE}; ls = {z: (q, n) for q, z, n, _ in D.LOW_SIDE}
zm = D.firmware_zmap()
for z in D.LEFT + D.RIGHT:
    u, port, bit = zm[z]
    pin = f"GP{'AB'[port]}{bit}"
    dip = {**{f"GPB{i}": i + 1 for i in range(8)}, **{f"GPA{i}": 21 + i for i in range(8)}}[pin]
    extra = ""
    if z in hs: extra = f"VCC via {hs[z][0]} (BC327)"
    if z in ls: extra = f"GND via {ls[z][0]} (2N7000)"
    w(f"| {z} | {'U2' if u == 0 else 'U3'} {pin} (DIP pin {dip}) | {extra} |")
w("\nZIF 13–28 are not connected.\n")

w("## Power switches\n")
w("| Switch | Part | ZIF | Control net | Driven by |")
w("|---|---|---|---|---|")
for q, z, n, d in D.HIGH_SIDE:
    w(f"| {q} | BC327 PNP, 1k base, 10k base–emitter | {z} (VCC) | {n} | {d} |")
for q, z, n, d in D.LOW_SIDE:
    w(f"| {q} | 2N7000, 100k gate pull-down | {z} (GND) | {n} | Nano {d} |")

w("\n## Nano pins\n")
w("| Nano pin | Signal | Goes to |")
w("|---|---|---|")
dest = {"EXP_CS": "U2 pin 11 + U3 pin 11", "MOSI": "U2 pin 13 + U3 pin 13", "MISO": "U2 pin 14 + U3 pin 14",
        "SCK": "U2 pin 12 + U3 pin 12", "EXP_RST": "U2 pin 18 + U3 pin 18, R21 10k to GND", "SDA": "U4 SDA, U5 SDA, R5",
        "SCL": "U4 SCL, U5 SCL, R4", "BTN": "SW1 → GND", "LED_STAT": "R6 1k → D4 → GND",
        "VIN_SENSE": "R1/R2 junction", "+5V": "+5V rail (C9, C10 at the pin)", "GND": "GND star point"}
for q, z, n, d in D.LOW_SIDE: dest[n] = f"{q} gate"
for num, name in sorted(D.NANO_LEFT + D.NANO_RIGHT):
    net = D.NANO_NET[name]
    w(f"| {num} {name.strip()} | {net} | {dest.get(net, '')} |")

w("\n## Expander straps\n")
w("| Pin | U2 | U3 |\n|---|---|---|")
w("| 9 VDD | +5V, C5 100 nF to pin 10 | +5V, C6 100 nF to pin 10 |")
w("| 10 VSS | GND | GND |")
w("| 15 A0 | GND | **+5V** |")
w("| 16 A1, 17 A2 | GND | GND |")
w("| 19 INTB, 20 INTA | nc | nc |")
w("| GPB5, GPB6 | spare | spare |")
w("\nBoth expanders share one chip-select. After reset both answer to address 0, so the firmware first writes IOCON.HAEN = 1 (both receive it), then addresses them as 0 and 1.\n")

w("## Bill of materials\n")
w("| Ref | Qty | Part | Notes |\n|---|---|---|---|")
for r in [
    ("A1", 1, "Arduino Nano, ATmega328P + CH340", "in 2 × 15-pin female headers"),
    ("U1", 1, "L7805CV, TO-220", "clip-on heatsink recommended at 12 V in"),
    ("U2, U3", 2, "MCP23S17-E/SP (SPDIP-28)", "SPI version, not the I²C MCP23017"),
    ("U4", 1, "INA219 breakout (0.1 Ω shunt)", "address 0x40"),
    ("U5", 1, "SSD1306 0.96″ 128×64 I²C OLED", "address 0x3C (some are 0x3D)"),
    ("J1", 1, "2.1 mm barrel jack", "12 V, centre positive"),
    ("J2", 1, "40-pin universal ZIF", "takes 0.3″ and 0.6″ DIPs"),
    ("D1", 1, "1N5819", "reverse-polarity protection"),
    ("D2", 1, "1N4007", "across U1, OUT → IN"),
    ("D3, D4", 2, "LED", "power, status"),
    ("Q1–Q4", 4, "BC327 (2N3906 also works below ~100 mA)", "VCC switches"),
    ("Q5–Q10", 6, "2N7000", "GND switches"),
    ("RS1–RS24", 24, "220 Ω", "one per ZIF contact"),
    ("R1", 1, "22 kΩ", "V_IN divider"), ("R2", 1, "10 kΩ", "V_IN divider"),
    ("R3, R6", 2, "1 kΩ", "LED resistors"), ("R4, R5", 2, "4.7 kΩ", "I²C pull-ups, if the modules lack them"),
    ("R7–R10", 4, "10 kΩ", "Q1–Q4 base–emitter"), ("R11–R14", 4, "1 kΩ", "Q1–Q4 base"),
    ("R15–R20", 6, "100 kΩ", "Q5–Q10 gate pull-downs"), ("R21", 1, "10 kΩ", "EXP_RST pull-down (expanders held in reset at boot)"),
    ("C1", 1, "100 µF 25 V electrolytic", "U1 input"), ("C2, C4, C5, C6, C8, C10", 6, "100 nF ceramic", "decoupling"),
    ("C3, C7, C9", 3, "10 µF electrolytic", "U1 output, VCC_SW, Nano 5V pin"),
    ("SW1", 1, "tactile switch", "ID / pin count"),
]:
    w(f"| {r[0]} | {r[1]} | {r[2]} | {r[3]} |")
open(os.path.join(ROOT, "docs/stage1/WIRING.md"), "w").write("\n".join(L) + "\n")
print("ok")
